### ISSUE TITLE
Option for first day of the week

### ISSUE THREAD

**Issue by GiFuJo** [birkholz/ClassicCalendar#3]
Would it be possible to add a simple switch in the addon options to toggle the start of the week between sunday and monday? Or maybe a dropdown option to choose the first day of the week? Were I'm from monday is considered the start of the week but in some cultures it's saturday.

Great addon, thanks a lot!

**Comment by birkholz** [comment]
The starting weekday is automatically changed by the game depending on the language the game is set to, and possibly other factors. For example, Español (EU) sets the starting weekday to Monday. However, we understand that people may want to change it from that default, so we're adding an option to do so. You'll be able to select the starting weekday in the addon's options in the next update.

**Comment by birkholz** [comment]
The option to change the starting weekday has been added to the addon options in v0.2.4beta, releasing now
