### ISSUE TITLE
WoW Classic Era - Move Calendar Option

### ISSUE THREAD

**Issue by maximus210793** [birkholz/ClassicCalendar#4]
Hi,
first of all great addon.
Could you add a feature to move the opened calendar around the screen, comparable to the moveable minimap button?
Thanks in advance!

**Comment by birkholz** [comment]
Hi,

This isn't something we plan to add to the calendar itself as there are other addons such as [MoveAny](https://www.curseforge.com/wow/addons/moveany) that support any window, including the calendar window. I suggest giving that a try.
